/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_robot_et_core_hardware_emotion_Emotion */

#ifndef _Included_com_robot_et_core_hardware_emotion_Emotion
#define _Included_com_robot_et_core_hardware_emotion_Emotion
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_robot_et_core_hardware_emotion_Emotion
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_robot_et_core_hardware_emotion_Emotion_init
  (JNIEnv *, jclass);

/*
 * Class:     com_robot_et_core_hardware_emotion_Emotion
 * Method:    setEmotion
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_robot_et_core_hardware_emotion_Emotion_setEmotion
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_robot_et_core_hardware_emotion_Emotion
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_robot_et_core_hardware_emotion_Emotion_close
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
