/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_robot_et_core_hardware_wakeup_WakeUp */

#ifndef _Included_com_robot_et_core_hardware_wakeup_WakeUp
#define _Included_com_robot_et_core_hardware_wakeup_WakeUp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_robot_et_core_hardware_wakeup_WakeUp
 * Method:    wakeUpInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_robot_et_core_hardware_wakeup_WakeUp_wakeUpInit
  (JNIEnv *, jclass);

/*
 * Class:     com_robot_et_core_hardware_wakeup_WakeUp
 * Method:    getWakeUpState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_robot_et_core_hardware_wakeup_WakeUp_getWakeUpState
  (JNIEnv *, jclass);

/*
 * Class:     com_robot_et_core_hardware_wakeup_WakeUp
 * Method:    getWakeUpDegree
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_robot_et_core_hardware_wakeup_WakeUp_getWakeUpDegree
  (JNIEnv *, jclass);

/*
 * Class:     com_robot_et_core_hardware_wakeup_WakeUp
 * Method:    setGainDirection
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_robot_et_core_hardware_wakeup_WakeUp_setGainDirection
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_robot_et_core_hardware_wakeup_WakeUp
 * Method:    wakeUpReset
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_robot_et_core_hardware_wakeup_WakeUp_wakeUpReset
  (JNIEnv *, jclass);

/*
 * Class:     com_robot_et_core_hardware_wakeup_WakeUp
 * Method:    faceWakeUpInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_robot_et_core_hardware_wakeup_WakeUp_faceWakeUpInit
  (JNIEnv *, jclass);

/*
 * Class:     com_robot_et_core_hardware_wakeup_WakeUp
 * Method:    getFaceWakeUpState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_robot_et_core_hardware_wakeup_WakeUp_getFaceWakeUpState
  (JNIEnv *, jclass);

/*
 * Class:     com_robot_et_core_hardware_wakeup_WakeUp
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_robot_et_core_hardware_wakeup_WakeUp_close
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
